version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/symfony
    networks:
      - symfony

  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  database:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    ports:
      - "8081:80"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge